name: Label & comment issues #the name of the workflow
on: # This action will trigger when an issue is reopened or opened.
  issues:
    types:
      - reopened
      - opened
      - closed # Add "closed" event type
  pull_request: # Add pull_request event
    types:
      - opened # Listen to opened pull requests

jobs: # The jobs that run in this workflow
  label_issues: # the first job is named as label_issues
    runs-on: ubuntu-latest # This job will run on the latest version of Ubuntu.
    permissions: # This job requires write access to issues in order to add labels and comment.
      issues: write
    steps: # The "steps" section contains the individual tasks that will be performed in this job.
      - name: attach label to issues # The name of the step
        uses: actions/github-script@v6 # This step uses the "actions/github-script" action to execute a script that adds labels to the issue.
        with:
          script: | # The script calls the GitHub REST API to add labels to the issue.
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })

      - name: Comment on new issue #this is another step that comments on the issue 
        uses: peter-evans/create-or-update-comment@v1 # This step uses the "peter-evans/create-or-update-comment" action to create or update a comment on the issue.
        if: github.event.action == 'opened' # Add condition to only execute when issue is opened
        with:
          issue-number: ${{ github.event.issue.number }} # The issue number is obtained from the context of the event that triggered the action.
          body: | # The body of the comment is a message thanking the user for opening the issue.
           Thanks for opening this issue! We'll take a look as soon as possible.

  comment_on_closed_issue: # New job to comment on closed issue
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Comment on issue when closed
        uses: actions/github-script@v4
        if: github.event.action == 'closed' # Add condition to only execute when issue is closed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue } = context.payload;
            const issueNumber = issue.number;
            const issueTitle = issue.title;
            const repo = context.repo.repo;

            // Comment on the issue when it's closed
            const message = `Issue ${issueNumber} (${issueTitle}) has been closed.`;
            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: repo,
              body: message
            });

  congratulate_first_pr: # this is implemented but it does not work
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.number == 1
    steps:
      - name: Congratulate on first pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request } = context.payload;
            const repo = context.repo.repo;
            const user = pull_request.user.login;
            const message = `Congratulations. This is your first pull request.`;
            github.issues.createComment({
              issue_number: pull_request.number,
              owner: context.repo.owner,
              repo: repo,
              body: message
            });
